### ISSUE TITLE
Option to set ioc2rpz.gui HostIP to 127.0.0.1 instead of 0.0.0.0?

### ISSUE THREAD

**Issue by dmgeurts** [Homas/ioc2rpz.dc#2]
How would one go about changing the default HostIP for ioc2rpz.gui when using docker-compose? This is related to: https://github.com/Homas/ioc2rpz/issues/43

I run ioc2rpz behind Nginx to apply LDAP auth via Keycloak, hence ioc2rpz.gui is set to listen to localhost and Nginx acts as a reverse proxy. I now manually edit the `hostconfig.json` file of the docker image, but I fear this will be broken if I update the image.

```
[...]
"PortBindings":{
    "443/tcp":[{"HostIp":"127.0.0.1","HostPort":"443"}],
    "80/tcp":[{"HostIp":"127.0.0.1","HostPort":"80"}]},
[...]
```

**Comment by dmgeurts** [comment]
Just worked out it's as simple as modifying the `docker-compose.yml` file as follows:

```
  ioc2rpz.gui:
    build:
      context: https://github.com/Homas/ioc2rpz.gui.git
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
```
